spring.application.name=ms-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MS-AUTH
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=usuarios-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MS-USUARIOS
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.server.webmvc.routes[2].id=categorias-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://MS-CATEGORIAS
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/categorias/**

spring.cloud.gateway.server.webmvc.routes[3].id=productos-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://MS-PRODUCTOS
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.server.webmvc.routes[4].id=pedidos-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://MS-PEDIDOS
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.server.webmvc.routes[5].id=inventario-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://MS-INVENTARIO
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/inventario/**

spring.cloud.gateway.server.webmvc.routes[6].id=pagos-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://MS-PAGOS
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.server.webmvc.routes[7].id=notificaciones-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://MS-NOTIFICACIONES
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.server.webmvc.routes[8].id=reportes-service
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://MS-REPORTES
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/reportes/**
